---
apiVersion: v1
kind: Service
metadata:
  name: drupal-service
spec:
  selector:
    app: drupal
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30095
      targetPort: 80